targets:
  TARGET:
    workspace:
      host: "https://dbc-108aefc7-f8df.cloud.databricks.com"

    variables:
      auth_strategy: "pat"
      pat_token: ""                          # injected by CI via DATABRICKS_TOKEN env var

      cluster_id:    ""                      # set after cluster is created
      warehouse_id:  "fc7181f319f9ab14"
      http_path:     "/sql/1.0/warehouses/fc7181f319f9ab14"

      uc_catalog: "workspace"
      uc_schema:  "default"
      uc_volume:  "trade-analytics"

      wheel_path: "/Volumes/workspace/default/trade-analytics/wheels/trade_analytics-latest.whl"

      dbt_schema:  "trade_analytics_dev"
      dbt_threads: "4"

      alert_email: "pravash.cse@gmail.com"

      namespace:     ""
      vault_url:     "https://eva.vault.azure.net"
      secret_path:   ""
      cert_role:     ""
      cert_path:     ""
      cert_key_path: ""

      org_id: "1757795806542983"